### ISSUE TITLE
ENHANCEMENT - More post meta properties for contentHub

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#305]
There are a few features that will mostly be of use when sending posts to the contentHub.

- [ ] Do not show on post lists
  - Available on site but hidden from index pages, related posts
  - still send post to contentHub
- [ ] Canonical URL (if the canonical URL is not this site)
  - We'll want to send this to the contentHub
- [ ] Language (mainly for the EMBL languages, English, Catalan, Spanish, French, German, Italian. But possibly for some other member states as well, Polish for example)
  - We'll want to send this to the contentHub
  - Default: english

This will be of use for both the News theme and other child themes (group site posts).

This is mainly in mind for the press release translations but all three feature would be useful in other scenarios.
